### ISSUE TITLE
Abstract core connection functionality into it's own package

### ISSUE THREAD

**Issue by ctrlsam** [FantasticFiasco/axis-js#270]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Split out the core Axis connection components and put them in another package folder.
This will allow changes to be made in one place instead of every package.
Also will be good for people who want to use the connection object for another Axis product.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by FantasticFiasco** [comment]
Hi @ctrlsam and welcome to the repository.

Are we talking about the following files, or is there a file you would like to reuse for your project?

- `Connection`
- `Protocol`
- `Request`
- `Response`
- `RequestError`
- `UnauthorizedError`
- `UnknownError`

**Comment by ctrlsam** [comment]
and `auth` folder
